version: '3.8'


services:

    db:
        image: mariadb:10.5.8
        restart: on-failure
        volumes: 
            - ./mariadb/charset.cnf:/etc/mysql/conf.d/charset.cnf
            - /tmp:/var/lib
        ports:
            - "3306:3306"
        domainname: mariadb
        hostname: db
        env_file: 
            - ./.env
    django:
        build:
            context: ../
            dockerfile: .docker/django/Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ../:/webapp/
        
        command: sh -c "sleep 5 &&
             pip install --no-cache-dir -r requirements.txt &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - db
        
        
        

    
    
    


    

