name: PyTest

on:
  push:
    branches:
      -master

  pull_request:
    branches:
      -master


#on:
#  schedule:
#    - cron: '*/15 * * * *'


 jobs:
    build:

      runs-on: ubuntu-latest

      step:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.2
        uses: actions/setup-python@v2
        with: 
          python-version: 3.9.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Lint with flake8
        run: |
          flake8

      - name: Pytest Run
        run: |
          pytest -s
      

