name: PyTest

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build Django Image
      uses: docker/build-push-action@v2
      with:
        file: .docker/django/Dockerfile

    - uses: actions/checkout@v2
    - name: Run docker-compose
      run: |
        cd .docker 
        docker-compose up -d

    - name: Pytest Run
      run: >
        docker exec django
        pytest -s